server:
  port: 2333

spring:
  datasource:
    url: jdbc:mysql://localhost/kotlin?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
